### ISSUE TITLE
Structure Documentation

### ISSUE THREAD

**Issue by ghost** [ISU-MAVRIC/MAVRIC-Systems#28]
We need to generate documentation for the structure of the system:

 - [ ] as a whole (base station, rover, communications equipment)
 - [ ] within the rover (raspberry Pi's, HATs, controllers)
 - [x] as ROS nodes

These may be combined/blurred some. This is not a one time task. We should probably have these for each milestone.

**Comment by Talonj123** [comment]
An example of the output from rqt_graph. This was generated on my laptop (not the rover) so the actual input/output nodes are missing. That is why the `Drive_Board_Hardware` namespace only has the 6 channels used by the `Drivetrain_Ouptut` node.

![rosgraph](https://user-images.githubusercontent.com/13686453/43362868-c06f058e-92ba-11e8-8cda-809d906faff4.png)

**Comment by Talonj123** [comment]
Here's the version generated from the rover when running. I set it to only show active topics, so the PWM drivers don't show all 16 channels.
![rosgraph](https://user-images.githubusercontent.com/13686453/43405657-ee3120da-93df-11e8-8056-b0d20722e4ac.png)

**Comment by Talonj123** [comment]
The only nodes that are not relocatable are the `*_Interface` nodes (relocating them breaks the base station interface) and the nodes in the `*_Board_HW` namespaces (relocating them requires re-wiring the rover. Everything else can be run on any board (functionally) As we get closet to a complete system, we will want to run CPU load analysis and see if any boards would benefit from re-balancing the system. We could go to a hardware-based division: Each board is responsible for a set of hardware (GPS, PWM, etc.) instead of each board handling the control of a single subsystem.

**Comment by Talonj123** [comment]
Another Update:
![rosgraph](https://user-images.githubusercontent.com/13686453/43536426-30991678-9582-11e8-8535-236b989b53ac.png)

**Comment by Talonj123** [comment]
I would like to put this into visio, powerpoint, or draw.io - but it has been changing somewhat rapidly as I add new nodes. Once we get more into testing/bugfixing, it will be more stable.

**Comment by Talonj123** [comment]
@jensenm7

**Comment by Talonj123** [comment]
With some changes to the drive system:
![rosgraph](https://user-images.githubusercontent.com/13686453/43660161-c7f9dc12-9723-11e8-9baf-9d40c09b37e1.png)
